package entidades;
// Generated 20-nov-2017 0:53:36 by Hibernate Tools 5.2.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Actores generated by hbm2java
 */
@Entity
@Table(name = "actores", catalog = "ADAT_UD2_A04_Cartelera1", uniqueConstraints = @UniqueConstraint(columnNames = "Nombre"))
public class Actores implements java.io.Serializable {

	private Integer codigo;
	private String nombre;
	private Date FNacimiento;
	private String nacionalidad;
	private Set<Reparto> repartos = new HashSet<Reparto>(0);

	public Actores() {
	}

	public Actores(String nombre, Date FNacimiento, String nacionalidad) {
		this.nombre = nombre;
		this.FNacimiento = FNacimiento;
		this.nacionalidad = nacionalidad;
	}

	public Actores(String nombre, Date FNacimiento, String nacionalidad, Set<Reparto> repartos) {
		this.nombre = nombre;
		this.FNacimiento = FNacimiento;
		this.nacionalidad = nacionalidad;
		this.repartos = repartos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Codigo", unique = true, nullable = false)
	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	@Column(name = "Nombre", unique = true, nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "F_nacimiento", nullable = false, length = 10)
	public Date getFNacimiento() {
		return this.FNacimiento;
	}

	public void setFNacimiento(Date FNacimiento) {
		this.FNacimiento = FNacimiento;
	}

	@Column(name = "Nacionalidad", nullable = false, length = 25)
	public String getNacionalidad() {
		return this.nacionalidad;
	}

	public void setNacionalidad(String nacionalidad) {
		this.nacionalidad = nacionalidad;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actores")
	public Set<Reparto> getRepartos() {
		return this.repartos;
	}

	public void setRepartos(Set<Reparto> repartos) {
		this.repartos = repartos;
	}

}
