package entidades;
// Generated 20-nov-2017 0:53:36 by Hibernate Tools 5.2.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Peliculas generated by hbm2java
 */
@Entity
@Table(name = "peliculas", catalog = "ADAT_UD2_A04_Cartelera1")
public class Peliculas implements java.io.Serializable {

	private Integer codigo;
	private String titulo;
	private Date fecha;
	private double presupuesto;
	private Set<Reparto> repartos = new HashSet<Reparto>(0);

	public Peliculas() {
	}

	public Peliculas(String titulo, Date fecha, double presupuesto) {
		this.titulo = titulo;
		this.fecha = fecha;
		this.presupuesto = presupuesto;
	}

	public Peliculas(String titulo, Date fecha, double presupuesto, Set<Reparto> repartos) {
		this.titulo = titulo;
		this.fecha = fecha;
		this.presupuesto = presupuesto;
		this.repartos = repartos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Codigo", unique = true, nullable = false)
	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	@Column(name = "Titulo", nullable = false, length = 50)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "Presupuesto", nullable = false, precision = 8)
	public double getPresupuesto() {
		return this.presupuesto;
	}

	public void setPresupuesto(double presupuesto) {
		this.presupuesto = presupuesto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "peliculas")
	public Set<Reparto> getRepartos() {
		return this.repartos;
	}

	public void setRepartos(Set<Reparto> repartos) {
		this.repartos = repartos;
	}

}
