package entidades;
// Generated 20-nov-2017 0:53:36 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Reparto generated by hbm2java
 */
@Entity
@Table(name = "reparto", catalog = "ADAT_UD2_A04_Cartelera1", uniqueConstraints = @UniqueConstraint(columnNames = {
		"C_actor", "C_pelicula" }))
public class Reparto implements java.io.Serializable {

	private Integer codigo;
	private Actores actores;
	private Peliculas peliculas;
	private String tipoPapel;

	public Reparto() {
	}

	public Reparto(String tipoPapel) {
		this.tipoPapel = tipoPapel;
	}

	public Reparto(Actores actores, Peliculas peliculas, String tipoPapel) {
		this.actores = actores;
		this.peliculas = peliculas;
		this.tipoPapel = tipoPapel;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Codigo", unique = true, nullable = false)
	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_actor")
	public Actores getActores() {
		return this.actores;
	}

	public void setActores(Actores actores) {
		this.actores = actores;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_pelicula")
	public Peliculas getPeliculas() {
		return this.peliculas;
	}

	public void setPeliculas(Peliculas peliculas) {
		this.peliculas = peliculas;
	}

	@Column(name = "tipoPapel", nullable = false, length = 10)
	public String getTipoPapel() {
		return this.tipoPapel;
	}

	public void setTipoPapel(String tipoPapel) {
		this.tipoPapel = tipoPapel;
	}

}
